"""Tenants table created

Revision ID: 002b1979fd05
Revises: 3ee341155de9
Create Date: 2026-06-24 15:03:01.119583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002b1979fd05'
down_revision: Union[str, Sequence[str], None] = '3ee341155de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tenant_email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tenants_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('id', 'tenant_email', 'owner_id', name=op.f('uq_tenants_id_tenant_email_owner_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_owner_id_users','tenants',type_='foreignkey')
    op.drop_table('tenants')
    # ### end Alembic commands ###
