"""Revoked JWT Tokens table created

Revision ID: 34a1a8a5d1af
Revises: 72d3412b9202
Create Date: 2026-06-24 17:54:53.084146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a1a8a5d1af'
down_revision: Union[str, Sequence[str], None] = '72d3412b9202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_jwt_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('token_type', sa.String(length=30), nullable=False),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], name=op.f('fk_revoked_jwt_tokens_session_id_user_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revoked_jwt_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_jwt_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_revoked_jwt_tokens_jti'))
    )
    op.create_index(op.f('ix_revoked_jwt_tokens_expires_at'), 'revoked_jwt_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_jwt_tokens_session_id'), 'revoked_jwt_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_revoked_jwt_tokens_user_id'), 'revoked_jwt_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('fk_revoked_jwt_tokens_session_id_user_sessions'), 'revoked_jwt_tokens', type_='foreignkey')
    op.drop_constraint(op.f('fk_revoked_jwt_tokens_user_id_users'), 'revoked_jwt_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_revoked_jwt_tokens_user_id'), table_name='revoked_jwt_tokens')
    op.drop_index(op.f('ix_revoked_jwt_tokens_session_id'), table_name='revoked_jwt_tokens')
    op.drop_index(op.f('ix_revoked_jwt_tokens_expires_at'), table_name='revoked_jwt_tokens')
    op.drop_table('revoked_jwt_tokens')
    # ### end Alembic commands ###
