"""Initial Migration

Revision ID: a3a7a62256ba
Revises: 
Create Date: 2026-06-10 13:34:57.507548

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'a3a7a62256ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
