"""User_Tenants table created

Revision ID: c40855ac930c
Revises: 7158c0586afe
Create Date: 2026-06-24 16:37:28.893204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40855ac930c'
down_revision: Union[str, Sequence[str], None] = '7158c0586afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('is_owner', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_user_tenants_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_tenants_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tenants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tenants')),
    sa.UniqueConstraint('user_id', 'tenant_id', name=op.f('uq_user_tenants_user_id_tenant_id'))
    )
    op.create_index(op.f('ix_user_tenants_tenant_id_is_active'), 'user_tenants', ['tenant_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_tenants_user_id_users'), 'user_tenants', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_tenants_tenant_id_tenants'), 'user_tenants', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_tenants_invited_by_user_id_users'), 'user_tenants', type_='foreignkey')
    op.drop_index(op.f('ix_user_tenants_tenant_id_is_active'), table_name='user_tenants')
    op.drop_table('user_tenants')
    # ### end Alembic commands ###
