import os
from typing import AsyncGenerator
from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy.orm import declarative_base
from app.config.config import settings


#Database URL
DATABASE_URL = settings.construct_db_url()


# Automatic names for constraints and indexes generated by SQLAlchemy/Alembic.
constraint_naming_convention = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(column_0_N_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=constraint_naming_convention)


# Initialize Base
Base = declarative_base(metadata=metadata)


# Create async engine for DB
async_engine = create_async_engine(
    DATABASE_URL,
    pool_pre_ping=True,        # Check connection health before executing the query
    pool_size=5,               # Standard pool size
    max_overflow=10,           # Max extra connections allowed under heavy load
)


# Initialize the Async Session Factory
AsyncSessionLocal = async_sessionmaker(
    bind=async_engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autocommit=False,
    autoflush=False
)


# Get Async Database session
async def get_async_db() -> AsyncGenerator[AsyncSession, None]:
    """
    Yields a database session context. Automatically ensures the session 
    is safely closed after the calling controller/route finishes execution.
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
        finally:
            await session.close()

